### ISSUE TITLE
Cannot scroll on Cockpit Tukit Firefox

### ISSUE THREAD

**Issue by IceWreck** [openSUSE/cockpit-tukit#21]
![image](https://github.com/openSUSE/cockpit-tukit/assets/18102790/3c551d8c-cd9f-4093-9834-63471328b3b0)

When the list of updates is long, you can't view the others without zooming out.

OS: OpenSUSE MicroOS

**Comment by rsimai** [comment]
Better late than never: tested with Cockpit 298 on SLE Micro 5.5 and Firefox 115.9.1esr (64-Bit). Scrolls just as it should so I assume the issue had been fixed meanwhile, this or that way. Please comment/reopen with version info if not. Thanks for your patience.
